# INFO: excellent example https://github.com/KenMwaura1/go-todo-api/blob/main/docker-compose.yaml
version: "3.9"
   
services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    # TODO: make the secret exportable
    environment:
      - POSTGRES_DB=gorm
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - backend-net


  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   environment:
  #     - SECRET_KEY=aabbcc
  #     - ENV_IS_SET

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    networks:
      - backend-net
    depends_on:
      - db

  # frontend:
  #   restart: unless-stopped
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   depends_on:
  #     - db
  #     - backend
networks:
  backend-net:
    name: backend-net
