version: "3.9"
   
services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gorm
      - POSTGRES_USER=gorm
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - SECRET_KEY=aabbcc
      - ENV_IS_SET

        # buggy
  # backend:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db


