on:
  push:
    branches: [main, dev/*, refactor/* ]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]
jobs:
  build:
    # Name the Job
    name: new feature linter
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GO: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_BASH: true
          VALIDATE_DOCKER: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_CSS: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
